# SPDX-License-Identifier: GPL-2.0-only

ccflags-y += -I$(srctree)
ccflags-y += -I$(srctree)/techpack/camera/include
ccflags-y += -I$(srctree)/techpack/camera/include/uapi

obj-$(CONFIG_SPECTRA_CAMERA) += ife_csid_hw/
obj-$(CONFIG_SPECTRA_CAMERA) += vfe_hw/
