# SPDX-License-Identifier: GPL-2.0-only


ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/camera/include
ccflags-y += -I$(srctree)/techpack/camera/include/uapi

obj-$(CONFIG_SPECTRA_CAMERA) += cam_irq_controller.o
