/* Auto-generated stub - lcd_kit_dpd.h
 * Original: panel-specific data generated by lcd_kit_parser.pl
 * This stub provides safe empty values to avoid NULL dereferences.
 */
#ifndef LCD_KIT_DPD_H
#define LCD_KIT_DPD_H

struct lcd_xml_string_name_map {
	const char *dtsi_string_name;
	const char *xml_string_name;
};

/* Empty sentinel - ARRAY_SIZE returns 1 but loop condition checks for non-NULL */
static struct lcd_xml_string_name_map xml_string_name_map[] = {
	{ "", "" },  /* Safe empty strings instead of NULL */
};

#endif /* LCD_KIT_DPD_H */
